# Insert the token of your Discord bot here.
# You should use a bot ONLY for Minecraft and NOT use your main bot for this
# as a token gives full access to the bot.
# Leaving this empty will make the plugin shutdown.
token: ''

# Insert the id of the broadcast channel.
# The broadcast channel is used for:
# - Broadcast players' advancements.
# - Broadcast players' deaths.
# - Broadcast players' messages in the chat.
# - Broadcast when a player joins/leaves the game.
broadcast-channel: ''

# The status channel that will store all the information about the server.
#
status-channel: ''

# The url image of the server.
# If you want to ignore this field just leave it empty.
server-image: ''

# DO NOT touch this option unless you know EXACTLY what you're doing.
# The message id of the server status.
status-message: ''

# How the {pf} placeholder should be displayed.
discord-prefix: "<dark_blue>[<blue>Discord<dark_blue>]<reset>"

# How the reference message should be displayed above the real message sent in Discord.
# in the Minecraft chat.
# Placeholders:
# {pf} - The prefix in the Minecraft chat to inform that the message was sent from Discord.
# {username} - The display name of who sent the referenced message.
# {user} - The real Discord name of who sent the message.
# {message} - The content of the referenced message in Discord.
discord-with-reply: "<i><dark_gray>replying to - </dark_gray></i><gray>{username}: {message}"

# How the message from Discord should be sent in the Mineraft chat.
# Placeholders:
# {pf} - The prefix in the Minecraft chat to inform that the message was sent from Discord.
# {username} - The display name of who sent the message.
# {user} - The real Discord name of who sent the message.
# {message} - The content of the message sent in Discord.
#
discord-format: "{pf} <white>{username}: {message}"

# The information provided in the status message.
# Always provide the port along with the IP like this: 'ip:port'
# I.e: '123.45.67.89:25565'
# Leave it empty if the ip does not exist for your server.
status-message-data:
  ip-java: '0.0.0.0'
  ip-bedrock: '0.0.0.0'