name: DiscordCraft
version: '${version}'
main: ofc.discord.DiscordCraft
api-version: '1.20'
commands:
  discord:
    description: Main plugin command.
    usage: /<command> <args>
    permission: discord.general
permissions:
  discord.general:
    description: Allows you to run the main command of the plugin.
    children:
      - discord.reloadconfig
    default: op
  discord.reloadconfig:
    description: Allows you to reload the configuration of the plugin.
    default: op